name: Auto Fetch M3U8 Links

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 自动配置匹配的 Chrome 和 ChromeDriver
    - name: Setup Chrome and WebDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install selenium

    - name: Run Fetch Script
      run: python fetch_m3u8.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add live_links.txt
        git diff --staged --quiet || git commit -m "update m3u8 links"
        git push
